Repository gentics/mesh, pull requests merged in 2018-02, with the labels that each got.

#279 Create Tests for (Micro-)Schema Validation
  core/src/test/java/com/gentics/mesh/core/utilities/AbstractValidateSchemaTest.java
  core/src/test/java/com/gentics/mesh/core/utilities/ValidateMicroSchemaTest.java
  core/src/test/java/com/gentics/mesh/core/utilities/ValidateSchemaTest.java
  core/src/test/java/com/gentics/mesh/test/context/AbstractMeshTest.java
  core/src/test/java/com/gentics/mesh/test/context/TestHttpMethods.java
Labels: f/schema

#290 Focalpoint endpoint fixes
  common/src/main/resources/i18n/translations_de.properties
  common/src/main/resources/i18n/translations_en.properties
  core/src/test/java/com/gentics/mesh/core/node/NodeImageResizeEndpointTest.java
  rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/image/FocalPoint.java
  rest-model/src/main/java/com/gentics/mesh/parameter/ImageManipulationParameters.java
  services/image-imgscalr/src/main/java/com/gentics/mesh/image/focalpoint/FocalPointModifier.java
Labels: bug, f/image

#300 NPE when keystore path contains no directory
  CHANGELOG.adoc
  api/src/main/java/com/gentics/mesh/etc/config/AuthenticationOptions.java
  core/src/main/java/com/gentics/mesh/cli/MeshImpl.java
Labels: bug

#299 Fix upload of files with empty filename possible
  CHANGELOG.adoc
  common/src/main/resources/i18n/translations_de.properties
  core/src/main/java/com/gentics/mesh/core/verticle/node/BinaryFieldHandler.java
  core/src/test/java/com/gentics/mesh/core/field/binary/BinaryFieldUploadEndpointTest.java
  rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
Labels: bug

#305 MeshRestClient: make HttpClientOptions customizeable
  CHANGELOG.adoc
  rest-client/src/main/java/com/gentics/mesh/rest/client/AbstractMeshRestHttpClient.java
  rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
Labels: enhancement

#306 Fix reindex fails because of transaction timeout
  CHANGELOG.adoc
  elasticsearch/src/main/java/com/gentics/mesh/search/index/AdminIndexHandler.java
Labels: bug
